site_name: FSD (unofficial)
nav:
  - Home: index.md
  - Preface:
      - 'Preamble': 'intro/preface.md'
      - 'Legal': 'intro/legal.md'
      - 'License': 'intro/gpl.md'
  - Introduction:
      - 'Terms used': 'intro/defs.md'
      - 'Overview of FSD': 'intro/overview.md'
  - Reference:
      - 'FSD packet overview': 'api/packet.md'
      - 'Adding/removing clients (#AP, #DP, #AA, #DA)': 'api/addclients.md'
      - 'Flight plan ($FP)': 'api/flightplan.md'
      - 'Position updates': 'api/pos.md'
      - 'METAR': 'api/metar.md'
      - 'Other packets': 'api/others.md'
theme: readthedocs
plugins:
  - search
  - autorefs
